packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    next: ^15.3.5
    next-themes: ^0.3.0
    react-hook-form: ^7.53.0
    react-day-picker: ^9.2.1
    react-resizable-panels: ^2.1.4
    "@types/react": ^19.0.0-rc.1
    "@types/react-dom": ^19.0.0
    socket.io-client: ^4.7.2
  ui:
    "@radix-ui/react-accordion": ^1.2.1
    "@radix-ui/react-alert-dialog": ^1.1.2
    "@radix-ui/react-aspect-ratio": ^1.1.0
    "@radix-ui/react-avatar": ^1.1.1
    "@radix-ui/react-checkbox": ^1.1.2
    "@radix-ui/react-collapsible": ^1.1.1
    "@radix-ui/react-context-menu": ^2.2.2
    "@radix-ui/react-dialog": ^1.1.2
    "@radix-ui/react-dropdown-menu": ^2.1.2
    "@radix-ui/react-hover-card": ^1.1.2
    "@radix-ui/react-label": ^2.1.0
    "@radix-ui/react-menubar": ^1.1.2
    "@radix-ui/react-navigation-menu": ^1.2.1
    "@radix-ui/react-popover": ^1.1.2
    "@radix-ui/react-progress": ^1.1.0
    "@radix-ui/react-radio-group": ^1.2.1
    "@radix-ui/react-scroll-area": ^1.1.0
    "@radix-ui/react-select": ^2.1.2
    "@radix-ui/react-separator": ^1.1.0
    "@radix-ui/react-slider": ^1.2.1
    "@radix-ui/react-slot": ^1.1.0
    "@radix-ui/react-switch": ^1.1.0
    "@radix-ui/react-tabs": ^1.1.0
    "@radix-ui/react-toggle": ^1.1.0
    "@radix-ui/react-toggle-group": ^1.1.0
    "@radix-ui/react-tooltip": ^1.1.3
    lucide-react: ^0.451.0
    cmdk: ^1.0.0
    vaul: ^1.0.0
  styling:
    tailwindcss: ^4.0.9
    "@tailwindcss/postcss": ^4.0.9
    tailwind-merge: ^3.2.0
    tw-animate-css: ^1.2.8
    postcss: ^8.4.47
    clsx: ^2.1.1
    class-variance-authority: ^0.7.0
  forms:
    "@hookform/resolvers": ^3.9.0
    input-otp: ^1.2.4
    zod: ^3.24.0
  charts:
    recharts: ^2.12.7
    embla-carousel-react: ^8.3.0
  utils:
    date-fns: ^4.1.0
  testing:
    "@testing-library/dom": ^10.4.0
    "@testing-library/jest-dom": ^6.5.0
    "@testing-library/user-event": ^14.5.2
    "@types/jsdom": ^21.1.7
    jsdom: ^25.0.1
  api:
    fastify: ^5.4.0
    fastify-blipp: ^3.1.0
    "@fastify/cors": ^10.0.0
    "@fastify/helmet": ^12.0.1
    "@fastify/sensible": ^6.0.1
    "@fastify/swagger": ^9.0.0
    "@fastify/swagger-ui": 5.2.3
    pino: ^8.21.0
    "fastify-socket.io": 5.1.0
    "socket.io": 4.8.1
    "@types/socket.io": 3.0.2
    "fastify-plugin": ^4.5.0
  analytics:
    "@vercel/analytics": ^1.3.1
    "@vercel/speed-insights": ^1.0.12
  build:
    tsx: ^4.19.1
    turbo: ^2.2.3
    rimraf: ^6.0.1
    "@vitejs/plugin-react-swc": ^3.7.1
  types:
    typescript: ^5.6.3
    "@types/node": ^20.0.0
    "@types/pino": 7.0.5
    "@types/bcryptjs": ^2.4.2
    "@types/jsonwebtoken": ^9.0.5
  lint:
    eslint: ^9.13.0
    "@typescript-eslint/eslint-plugin": ^8.12.1
    "@typescript-eslint/parser": ^8.12.1
    eslint-config-prettier: ^9.1.0
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-react: ^7.37.2
    eslint-plugin-react-hooks: ^5.0.0
    eslint-plugin-turbo: ^2.2.3
    globals: ^15.11.0
    "@next/eslint-plugin-next": ^15.3.5
    "@biomejs/biome": ^1.9.4
  orm:
    prisma: ^5.0.0
    "@prisma/client": ^5.0.0
catalog:
  "@next/eslint-plugin-next": ^15.3.5
  "@turbo/gen": ^2.2.3
  "@types/node": ^20.0.0
  "@types/react": ^19.0.0-rc.1
  "@types/react-dom": ^19.0.0
  "@typescript-eslint/eslint-plugin": ^8.12.1
  "@typescript-eslint/parser": ^8.12.1
  eslint: ^9.13.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-turbo: ^2.2.3
  globals: ^15.11.0
  rimraf: ^6.0.1
  sonner: ^2.0.6
  tsx: ^4.19.1
  turbo: ^2.2.3
  typescript: ^5.6.3
  typescript-eslint: ^8.12.1
  jsonwebtoken: ^9.0.2
  bcryptjs: ^2.4.3
